# TODO: Replace this with your actual tmux configuration.
# This is a minimal starter config.

# Tmux Plugin Manager plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

# Switch leader prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix


# Easier pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Increase history limit
set -g history-limit 100000

# Enable 256 colors
set-option -sa terminal-overrides ",xterm*:Tc":w
set -g default-terminal "tmux-256color"

# This is so it can stop asking to enter passphrase
set -g update-environment "SSH_AUTH_SOCK"
setenv -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock

# Enable mouse mode
set -g mouse on

#Enables copy/paste in neovim over ssh
set -g set-clipboard on


#rename window
bind-key r command-prompt "rename-window %%:"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# key bindings for swapping windows
bind-key C-h swap-window -t -1\; select-window -t -1
bind-key C-l swap-window -t +1\; select-window -t +1
bind-key C-m command-prompt -p "Move window to index:" "move-window -b -t %%"

# Open split in same directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


# Better yanking
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Navigate between vim and tmux
set -g @plugin 'christoomey/vim-tmux-navigator'

# Persist sessions
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Easy reload of config file
bind-key R source-file ~/dotfiles/tmux/.tmux.conf; display "Config Reloaded!"
# Initialize TPM (keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
