# TODO: Replace this with your actual tmux configuration.
# This is a minimal starter config.

# Tmux Plugin Manager plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @plugin 'tmux-plugins/tpm'

# Switch leader prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Easier pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Increase history limit
set -g history-limit 100000

# Enable 256 colors
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color"

# Enable mouse mode
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Vi-mode
set-window-option -g mode-keys vi

# Open split in same directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Catppuccin config
set -g @catppuccin_flavor "latte"
set -g @catppuccin_window_status_style "rounded"

# Easy reload of config file
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Initialize TPM (keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
